name: Nginx Builder

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Nginx Version'
        required: true
        default: '1.27.3'

jobs:
  Nginx:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    env:
      VERSION: ${{ github.event.inputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        id: push
        uses: docker/build-push-action@v6
        with:
          file: ./Nginx
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/nginx:${{ env.VERSION }}
