name: PHP Builder

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'PHP Version'
        required: true
        default: '8.4.3'

jobs:
  PHP:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    steps:
      - name: Set version number
        run: echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        id: push
        uses: docker/build-push-action@v6
        with:
          file: ./PHP
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/php:${{ env.VERSION }}
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ghcr.io/${{ github.repository_owner }}/php
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
