name: PHP Builder

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'PHP Version'
        required: true
        default: '8.4.2'

jobs:
  PHP:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    env:
      VERSION: ${{ github.event.inputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        id: push
        uses: docker/build-push-action@v6
        with:
          file: ./PHP
          platforms: linux/amd64
          build-args: |
            VERSION=${{ env.VERSION }}
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/php:${{ env.VERSION }}
